// User
export const USERLOGIN = 'USER/LOGIN';
export const USERLOGOUT = 'USER/LOGOUT';
export const USERUPDATE = 'USER/UPDATE';
export const USERADDCOLLECTION = 'USER/ADD_COLLECTION';
export const USERDELETECOLLECTION = 'USER/DELETE_COLLECTION';
export const USERADDHISTORY = 'USER/ADD_HISTORY';
export const USERDELETEHISTORY = 'USER/DELETE_HISTORY';

// Cart
export const CARTADD = 'CART/ADD';
export const CARTDELETE = 'CART/DELETE';
export const CARTUPDATE = 'CART/UPDATE';
export const CARTINIT = 'CART/INIT';

// Collection
export const COLLECTIONADD = 'COLLECTION/ADD';
export const COLLECTIONDELETE = 'COLLECTION/DELETE';
export const COLLECTIONUPDATE = 'COLLECTION/UPDATE';
export const COLLECTIONINIT = 'COLLECTION/INIT';

// Category | History
export const CATEGORYDATA = 'CATEGORY/DATA'
export const CATEGORYACTIVE = 'CATEGORY/ACTIVE'
export const HISTORYADD = 'HISTORY/ADD';
export const HISTORYDELETE = 'HISTORY/DELETE';
